### ISSUE TITLE
[Bug] Battletoads levels didn't decoded.

### ISSUE THREAD

**Issue by Tippek** [romhack/habsentminded#1]
Names of levels didn't decoded. After decode - encode without any changes names of levels did broken.

**Comment by romhack** [comment]
Thanks for that: Battletoads use the last text block only for level names, though Bt&DD keep last text block blank. That slightly changes decoding logic, so now there are 2 versions of program separate for Bt and for Bt&DD.
Please, check latest [release archive](https://github.com/romhack/habsentminded/releases/latest)
